### PR TITLE
Minor fixes, scroll bottom

### PR DESCRIPTION
**Pull request by RGA15071999**
Changes made:
1.I am not pushing directly since scrolling code is using getElementById()
2. Added code to check user. If input is empty, request will not be sent
3. Some minor errors.
4. It may give conflicts with 90% probability.

### CODE REVIEW

**Comment by fxfactorial** [comment]
@RGA15071999 Thanks, but you don't need to use getElementById, cause we can do a ref. 

Check out the current implementation. The bug is that it scrolls always to the bottom because of the setInterval of getting new messages. 

We can fix that and then this scrolldown issue will be fixed as well

**Comment by fxfactorial** [comment]
@RGA15071999 Thanks, but you don't need to use getElementById, cause we can do a ref. 

Check out the current implementation. The bug is that it scrolls always to the bottom because of the setInterval of getting new messages. 

We can fix that and then this scrolldown issue will be fixed as well

**Comment by fxfactorial** [comment]
@RGA15071999 Thanks, but you don't need to use getElementById, cause we can do a ref. 

Check out the current implementation. The bug is that it scrolls always to the bottom because of the setInterval of getting new messages. 

We can fix that and then this scrolldown issue will be fixed as well

**Comment by fxfactorial** [comment]
@RGA15071999 Thanks, but you don't need to use getElementById, cause we can do a ref. 

Check out the current implementation. The bug is that it scrolls always to the bottom because of the setInterval of getting new messages. 

We can fix that and then this scrolldown issue will be fixed as well

**Comment by RGA15071999** [comment]
I wrote something like this but because we keep updating I thought
getElement will be more proper for our current logic. I am thinking about
ways to fix it.

**Comment by fxfactorial** [comment]
@RGA15071999 Let's start with a web socket implementation, when that works then this issue will go away

**Comment by fxfactorial** [comment]
@RGA15071999 I got one up :)

**Pull request closed without merging**
